### ISSUE TITLE
monitor.isOverTop等判断方法只返回true

### ISSUE THREAD

**Issue by bbfpl** [bpuns/easy-dnd#1]
在使用vue版本里example1案例中
在B.vue的dragOver方法添加测试代码如下
  dragOver(monitor) {
    console.log('A在B中移动',monitor.isOverTop())
  },
将A拖拽到B的下方显示还是true.
不知道是不是我使用错误，请作者大大指正

**Comment by bpuns** [comment]
我中午下班看下

**Comment by bpuns** [comment]
@bbfpl 我试了是正常的诶

![GIF 2023-10-17 11-04-22](https://github.com/bpuns/easy-dnd/assets/42114461/49a21a0d-ec96-4e00-9688-082b741ca740)

**Comment by bbfpl** [comment]
感谢大佬,我再试试

**Comment by bbfpl** [comment]
大佬，我测试发现在Firefox下会出现这种情况，chrome是没问题的。

**Comment by bpuns** [comment]
@bbfpl 最新版本解决了，原因是Firefox下drag不允许获取clientX与clientY，我将此操作移动到dragover中
