### ISSUE TITLE
不能拖拽svg元素

### ISSUE THREAD

**Issue by bbfpl** [bpuns/easy-dnd#2]
drag.dragRef 使用在div下没有问题，但是使用svg元素就提示错误：class Drag调用subscribe方法前必须调用registerDom方法

**Comment by bpuns** [comment]
MDN官方文档说明了拖拽api不能应用在Svg元素上，地址：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/draggable

**Comment by bpuns** [comment]
@bbfpl MDN官方文档说明了拖拽api不能应用在Svg元素上，地址：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/draggable

**Comment by bbfpl** [comment]
@bpuns 好的 感谢大佬解惑
