### ISSUE TITLE
拖拽能否支持拖动预览的功能?

### ISSUE THREAD

**Issue by bbfpl** [bpuns/easy-dnd#3]
大佬你好，
拖拽能否支持拖动预览的功能呢，有点类似这种效果https://code.juejin.cn/pen/7300834276365303843
拖动的时候预览的图片或者dom会变成实际放置的大小，这个功能为了拖拽后直接就可以对齐控件。

**Comment by bpuns** [comment]
你想要的是这种效果吗？https://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer @bbfpl

**Comment by bbfpl** [comment]
@bpuns 有点像这种效果 https://react-dnd.github.io/react-dnd/examples/customize/handles-and-previews

**Comment by bpuns** [comment]
@bbfpl 这两个应该都是拖拽中把拖拽元素隐藏掉，然后通过clone或者自己生成一个要拖拽显示的dom，拖拽过程一直显示它，这个可以周末的时候研究下react-dnd的源码，看下它怎么实现的，然后再想api要如何封装

**Comment by bbfpl** [comment]
大佬v5
